[package]
name = "test_rust"
version = "0.1.0"
authors = ["Todd Pickell <tapickell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#rust-crypto = "0.2.36"
crypto-hash = "0.3.4"
time = "0.2.16"
